#pragma once
// Effect preset parameters — auto-generated by Firmware Builder
// Modify via the Builder UI (control/ui/flasher.html) or edit directly

#ifndef PRESET_FLAME_HUE_MAX
#define PRESET_FLAME_HUE_MAX      28   // max hue (0-255): 28 ≈ red→yellow range
#endif
#ifndef PRESET_FLAME_BRIGHT_MIN
#define PRESET_FLAME_BRIGHT_MIN  120   // min brightness for flame flicker (0-255)
#endif
#ifndef PRESET_FLAME_SAT_MIN
#define PRESET_FLAME_SAT_MIN     210   // min saturation (0-255)
#endif
#ifndef PRESET_RAINBOW_STEP
#define PRESET_RAINBOW_STEP        3   // hue increment per render frame
#endif
#ifndef PRESET_SPARKLE_FADE
#define PRESET_SPARKLE_FADE      180   // fade multiplier for non-lit LEDs (0-255)
#endif
