[platformio]
default_envs = pedal

[env]
platform      = espressif32
framework     = arduino
monitor_speed = 115200
build_flags =
    -D GROUP_ID=1

[env:pedal]
board = esp32dev
build_flags =
    ${env.build_flags}
    -D OTA_HOSTNAME='"pedal"'

[env:pedal-ota]
board = esp32dev
upload_protocol = espota
upload_port = pedal.local
build_flags =
    ${env:pedal.build_flags}
