[platformio]
default_envs = staff
extra_configs = ../wifi_credentials.ini

[env]
platform    = espressif32
framework   = arduino
board_build.partitions = min_spiffs.csv
board_build.flash_size = 4MB
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.7.0
    ArduinoOTA

[env:staff]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
upload_protocol = esptool
build_flags =
    -D GROUP_ID=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D FASTLED_ESP32_FLASH_LOCK=1
    -D IMU_SDA=6
    -D IMU_SCL=7
    -D OTA_HOSTNAME='"staff-s3"'
    -D DEVICE_ROLE='"staff"'

[env:staff-ota]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
upload_protocol = espota
upload_port = staff-s3.local
build_flags =
    -D GROUP_ID=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D FASTLED_ESP32_FLASH_LOCK=1
    -D IMU_SDA=6
    -D IMU_SCL=7
    -D OTA_HOSTNAME='"staff-s3"'
    -D DEVICE_ROLE='"staff"'

[env:staff-c3]
board = esp32-c3-devkitm-1
board_build.flash_size = 4MB
upload_protocol = esptool
build_flags =
    -D GROUP_ID=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D IMU_SDA=5
    -D IMU_SCL=6
    -D OTA_HOSTNAME='"staff-c3"'
    -D DEVICE_ROLE='"staff"'

[env:staff-c3-ota]
board = esp32-c3-devkitm-1
board_build.flash_size = 4MB
upload_protocol = espota
upload_port = staff-c3.local
build_flags =
    -D GROUP_ID=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D IMU_SDA=5
    -D IMU_SCL=6
    -D OTA_HOSTNAME='"staff-c3"'
    -D DEVICE_ROLE='"staff"'

