[platformio]
default_envs = mic-s3

[env]
platform      = espressif32
framework     = arduino
monitor_speed = 115200
lib_deps =
    kosme/arduinoFFT@^2.0.1
build_flags =
    -D GROUP_ID=1

[env:mic]
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D OTA_HOSTNAME='"mic-c3"'

[env:mic-ota]
board = esp32-c3-devkitm-1
upload_protocol = espota
upload_port = mic-c3.local
build_flags =
    ${env:mic.build_flags}

[env:mic-s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
upload_protocol = esptool
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D MIC_ADC_PIN=4
    -D OTA_HOSTNAME='"mic-s3"'

[env:mic-s3-ota]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_build.partitions = min_spiffs.csv
upload_protocol = espota
upload_port = mic-s3.local
build_flags =
    ${env:mic-s3.build_flags}
